steps:
  - name: gradle:jdk17 #使用gradle jdk17 的docker image
    entrypoint: ./gradlew
    args: ['clean', 'build']
serviceAccount: 'projects/tli-bi/serviceAccounts/YOUR_NEW_SERVICE_ACCOUNT@tli-bi.iam.gserviceaccount.com'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
