steps:
  - name: gradle:jdk17 #使用gradle jdk17 的docker image
    entrypoint: ./gradlew
    args: ['clean', 'build']
serviceAccount: 'projects/your-project-id/serviceAccounts/450302107744-compute@developer.gserviceaccount.com'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
